SwiftDapper/AspNetCoreDemo/Models/Response.cs
namespace AspNetCoreDemo.Models
{
    public class Response<TItem>
    {
        public bool IsSuccessful { get; set; } = true;

        public string Message { get; set; } = string.Empty;

        public TItem Data { get; set; }
    }
}

SwiftDapper/AspNetCoreDemo/Models/Swift.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreDemo.Models
{
    public class Swift
    {
        public int Id { get; set; }

        [Required]
        public string BasicHeaderBlock { get; set; }

        [Required]
        public string ApplicationHeaderBlock { get; set; }

        public string? UserHeaderBlock { get; set; }

        [Required]
        public string TransactionReferenceNumber { get; set; }

        public string? RelatedReference { get; set; }

        [Required]
        public string Narrative { get; set; }

        [Required]
        public string TrailerBlockMac { get; set; }
        
        [Required]
        public string TrailerBlockChk { get; set; }
    }
}

SwiftDapper/AspNetCoreDemo/Controllers/Api/SwiftApiController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using AspNetCoreDemo.Services.Contracts;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreDemo.Controllers
{
    [ApiController]
    [Route("api/swift")]
    public class SwiftApiController : ControllerBase
    {
        private readonly ISwiftService swiftService;
        private readonly IWebHostEnvironment environment;
        private readonly ILoggerManager logger;

        public SwiftApiController(
            ISwiftService swiftService,
            IWebHostEnvironment environment,
            ILoggerManager logger)
        {
            this.swiftService = swiftService;
            this.environment = environment;
            this.logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAsync()
        {
            var result = await this.swiftService.GetAllAsync();
            if (!result.IsSuccessful)
            {
                logger.LogWarn(Constants.NoRecordsErrorLog);
                return this.StatusCode(StatusCodes.Status404NotFound, result.Message);
            }
            logger.LogInfo(Constants.GetAllSuccessful);
            return this.StatusCode(StatusCodes.Status200OK, result.Data);
        }

        [HttpPost("upload")]
        public async Task<IActionResult> UploadFileAsync(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                logger.LogInfo(Constants.NotFileSelectedErrorLog);
                return BadRequest(Constants.FileSelectionError);
            }

            if (Path.GetExtension(file.FileName).ToLower() != Constants.FormatFile)
            {
                logger.LogInfo(Constants.FileSelectionErrorLog);
                return BadRequest(Constants.FileSelectionError);
            }

            try
            {
                var uploadsFolder = Path.Combine(environment.WebRootPath, "files");

                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                var filePath = Path.Combine(uploadsFolder, file.FileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }

                var result = await this.swiftService.CreateAsync(filePath);
                if (!result.IsSuccessful)
                {
                    logger.LogError(result.Message);
                    return BadRequest(result.Message);
                }
                logger.LogInfo(Constants.FileUploadSuccessful);
                return Ok(Constants.FileUploadSuccessful);
            }
            catch (Exception ex)
            {
                logger.LogError(Constants.FileUploadError + ex.Message);
                return BadRequest(Constants.FileUploadError + ex.Message);
            }
        }
    }
}

SwiftDapper/AspNetCoreDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;
using System;
using AspNetCoreDemo.Services.Contracts;
using Microsoft.AspNetCore.Hosting;

namespace AspNetCoreDemo.Controllers.Web
{
    public class HomeController : Controller
    {
        private readonly ISwiftService swiftService;
        private readonly IWebHostEnvironment environment;
        private readonly ILoggerManager logger;

        public HomeController(
            ISwiftService swiftService, 
            IWebHostEnvironment environment,
            ILoggerManager logger
            )
        {
            this.swiftService = swiftService;
            this.environment = environment;
            this.logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            logger.LogInfo(Constants.VisitedSwiftIndexViewLog);
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadTextFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                logger.LogInfo(Constants.NotFileSelectedErrorLog);
				return View(Constants.Index, Constants.FileSelectionError);
            }

            if (Path.GetExtension(file.FileName).ToLower() != Constants.FormatFile)
            {
                logger.LogInfo(Constants.FileSelectionErrorLog);
                return View(Constants.Index, Constants.FileSelectionError);
            }

            try
            {
                var uploadsFolder = Path.Combine(environment.WebRootPath, "files");

                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                var uniqueFileName = DateTime.Now.ToString(Constants.FormatDate) + "_" + file.FileName;
                var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }

                var result = await this.swiftService.CreateAsync(filePath);
                if (!result.IsSuccessful)
                {
                    logger.LogError(result.Message);
                    return this.View(Constants.Index, result.Message);
                }
                logger.LogInfo(Constants.FileUploadSuccessful);
                return this.View(Constants.Index, Constants.FileUploadSuccessful);
			}
            catch (Exception ex)
            {
                logger.LogError(Constants.FileUploadError + ex.Message);
                return View(Constants.Index, Constants.FileUploadError + ex.Message);
            }
        }
    }
}

SwiftDapper/AspNetCoreDemo/Controllers/SwiftController.cs
using AspNetCoreDemo.Models;
using AspNetCoreDemo.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Threading.Tasks;

namespace AspNetCoreDemo.Controllers
{
    public class SwiftController : Controller
    {
        private readonly ISwiftService swiftService;
        private readonly ILoggerManager logger;

        public SwiftController(
            ISwiftService swiftService,
            ILoggerManager logger)
        {
            this.swiftService = swiftService;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var result = await this.swiftService.GetAllAsync();
            if (!result.IsSuccessful)
            {
                logger.LogWarn(Constants.NoRecordsErrorLog);
                this.ViewData[Constants.ErrorMessage] = result.Message;
                return View(result.Data);
            }
            logger.LogInfo(Constants.VisitedSwiftIndexViewLog);
            return View(result.Data);
        }
    }
}

SwiftDapper/AspNetCoreDemo/Views/Home/Index.cshtml
@{
    this.ViewData["Title"] = "Home";
}
@model String 
@using AspNetCoreDemo.Controllers
@using (Html.BeginForm("UploadTextFile", "Home", FormMethod.Post, new { enctype = "multipart/form-data" })) ;

<br/>

<form asp-controller="Home" asp-action="UploadTextFile" enctype="multipart/form-data" method="post">
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-hover" style="width: 50%;">
            <thead class="table-dark">
                <tr>
                    <th class="text-center">Upload Form</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td>
                        Select a .txt file:
                        <br/>
                        <input type="file" name="file" id="file" class="form-control" style="width: 100%;height: 45px;" />
                        <p class="lead">@this.Model</p>
                        <button type="submit" class="btn btn-primary">Upload .txt file</button>
                       </td>    
                    </tr>
            </tbody>
        </table>
    </div>
</form>

SwiftDapper/AspNetCoreDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Swift file - @this.ViewData["Title"]</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   	<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
            <div class="container">
                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Welcome to SwiftFile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item ml-3">
                            <a class="nav-link text-dark" asp-controller="Swift" asp-action="Index">Swifts</a>
                        </li>
                        <li class="nav-item ml-3">
                            <a class="nav-link text-dark" href="/api/swagger">Swagger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
	</header>

	<div class="body-content">
		@RenderBody()
	</div>

	<footer>
		<small>© Copyright SwiftFile @DateTime.Now.Year</small>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

SwiftDapper/AspNetCoreDemo/Views/Swift/Index.cshtml
@model IEnumerable<Swift>
@{
    this.ViewData["Title"] = "Swifts";
}
<body>
    <h2>Swifts</h2>
    <br/><br/>
    @if (ViewData["ErrorMessage"] != null)
                        {
                            <div class="row">
                                <div class="col text-center">
                                    <p>&nbsp;</p>
                                    <p>@ViewData["ErrorMessage"]</p>
                                </div>
                            </div>

                        }
                        else
                        {
    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-hover">
            <thead class="table-dark">
                <tr>
                    <th class="text-center">Blocks</th>
                    <th class="text-center">Narrative</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var swift in Model)
                {
                    <tr>
                        <td>ID: @swift.Id
                            <br/><br/>
                            Basic Header Block: @swift.BasicHeaderBlock
                            <br /><br />
                            Application Header Block: @swift.ApplicationHeaderBlock
                            <br /><br />
                            User Header Block: @swift.UserHeaderBlock
                            <br/><br/>
                            Transaction Reference Number: @swift.TransactionReferenceNumber
                            <br /><br />
                            Related Reference: @swift.RelatedReference
                            <br /><br />
                            Trailer Block Mac: @swift.TrailerBlockMac
                            <br /><br />
                            Trailer Block Chk: @swift.TrailerBlockChk
                        <td>
                                    @Html.Raw(@swift.Narrative.Replace("\r\n", "<br />"))
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    }
</body>
    